### ISSUE TITLE
山人全息码

### ISSUE THREAD

**Issue by ywxt** [sgalal/awesome-rime#15]
[ywxt/sunman](https://github.com/ywxt/sunman)

山人输入方案

**Comment by ywxt** [comment]
可以添加一下吗？

**Comment by sgalal** [comment]
可以重命名成 rime-sunman，并且把 yaml 放在根目录嘛？因为这样符合 rime 命名习惯，而且也可以用 plum 直接安装。

**Comment by ywxt** [comment]
改好了[rime-sunman](https://github.com/ywxt/rime-sunman)

**Comment by sgalal** [comment]
谢谢！
