### ISSUE TITLE
谷歌五笔86

### ISSUE THREAD

**Issue by bosconb** [sgalal/awesome-rime#4]
[谷歌五笔86版](https://github.com/hchunhui/rime-wubi86go)

**Comment by sgalal** [comment]
Would you please make a pull request?

**Comment by bosconb** [comment]
见笑了，本人不是IT从业者，不太会玩git。等我抽空整理了再来pull。

**Comment by BlindingDark** [comment]
@bosconb 直接在网页上编辑然后点下一步下一步就好啦
