### ISSUE TITLE
添加 Rime 韩语输入方案

### ISSUE THREAD

**Issue by einverne** [sgalal/awesome-rime#7]
首先感谢一下作者整理了现在的Rime输入方案，之前想找韩语输入方案的时候确实花了一些时间，如果有这个列表，后续有人想要查找不同的输入方案就方便很多了。

另外 [rime-hangul](https://github.com/einverne/rime-hangul) 是当时我找到的韩语输入方案，其中除了 rime-hangyl 是官方提供的方案，下面两个是我征求一位[台湾](http://deltazone.pixnet.net/blog/post/264243364)友人同意放到GitHub上面的。

- hangeul-2-set
- hangeul 韩语形码

如果可以的话，我可以提一个PR把这两个方案也放到这个列表中。

**Comment by ayaka14732** [comment]
谢谢！欢迎 pr

**Comment by sgalal** [comment]
谢谢！欢迎 pr
